[package]
name = "tppp"
version = "1.1.2"
edition = "2021"
license = "Apache-2.0"
description = "a test project"
repository = "https://github.com/liuzsen/abcc"
authors = ["liuzsen"]

[workspace]
members = ["tppa"]

[dependencies]
